
export {default as HomePage} from './home/HomePage'
export {default as AboutPage} from './about/AboutPage'
export {default as BlogPage} from './blog/BlogPage'
export {default as ContactPage} from './contact/ContactPage'
export {default as BlogDetailPage} from './blog/BlogDetailPage'
export {default as NotAuthorized} from './403'
export {default as Notfound} from './404'
export {default as InternalServerError} from './500'
export {default as ForgotPassword} from './forgotPassword'
export {default as ChangePassword} from './changePassword'
