export {default as HomePage} from './home/HomePage'
export {default as AboutPage} from './about/AboutPage'
export {default as BlogPage} from './blog/BlogPage'
export {default as ContactPage} from './contact/ContactPage'
export {default as BlogDetailPage} from './blog/BlogDetailPage'
